apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appInfo.name }}
  namespace: {{ .Values.appInfo.namespace }}
  labels:
    {{- range $key, $value := .Values.appInfo.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .protocol | lower }}-{{ .port }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- range $key, $value := .Values.podInfo.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if eq .Values.service.sessionAffinity "ClientIP" }}
  sessionAffinityConfig:
    timeoutSeconds: 10800
  {{- end}}
  type: {{ .Values.service.type }}