# should named as `settings.yml`

settings:
  listen_addr: 127.0.0.1:18082
  producer_forks: 3  # forks for each tag
  producer:
    msg_batch_size: 1000
    max_wait_sec: 5
    backend_addr: 127.0.0.1:24225
    each_tag_chan_len: 8000
    retry_chan_len: 10000
  journal:
    buf_dir_path: /Users/laisky/Downloads/buf
    buf_file_bytes: 209315200  # 200 MB
    journal_out_chan_len: 100000
    commit_id_chan_len: 100000
  acceptor:
    out_chan_size: 100000
    max_rotate_id: 100000000
  acceptor_filters:
    out_buf_len: 50000
    reenter_chan_len: 5000
    tenants:
      spark:
        msg_key: log
        identifier: container_id
        ignore_regex: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2},\d{3} +\[
      spring:
        rules:
          - msg_key: log
            new_tag: cp.{env}
            regexp: ms:cp
          - msg_key: log
            new_tag: bot.{env}
            regexp: ms_\w+\ {0,}\|
          - msg_key: log
            new_tag: app.spring.{env}
            regexp: .*
  post_filters:
    reenter_chan_len: 5000
    out_chan_size: 10000
    tenants:
      default:
        msg_key: log
        max_len: 307200
  kafka_recvs:
    interval_num: 1000
    interval_sec: 30
    tenants:
      spark:
        nconsumer: 10
        msg_key: log
        meta:
          container_id: "go-concator"
        groups:
          sit: paas_spark_log_sit_v2
          uat: paas_spark_log_uat_v2
          perf: paas_spark_log_perf_v2
          prod: paas_spark_log_prod_v2
        topics:
          sit: logaiSit
          uat: logaiUat
          perf: logaiPerf
          prod: logaiPro
        tags:
          sit: spark.sit
          uat: spark.uat
          perf: spark.perf
          prod: spark.prod
        brokers:
          sit:
            - 1.1.1.11:9092
            - 1.1.1.12:9092
            - 1.1.1.13:9092
            - 1.1.1.1.65:9092
  dispatcher:
    out_chan_size: 10000
  tag_filters:
    internal_chan_size: 10000
    tenants:
      connector:
        tag: connector # compatable before paas-130
        tags:
          - connector
          - gateway
        msg_key: log
        pattern: (?ms)^(?P<time>.{23}) {0,}\| {0,}(?P<app>[^ ]+) {0,}\| {0,}(?P<level>[^ ]+) {0,}\| {0,}(?P<thread>[^ ]+) {0,}\| {0,}(?P<class>[^ ]+) {0,}\| {0,}(?P<line>\d+) {0,}([\|:] {0,}(?P<args>\{.*\}))?([\|:] {0,}(?P<message>.*))?
        is_remove_orig_log: true
      concator:
        config:
          max_length: 100000
        tenants:
          test:
            msg_key: log
            identifier: container_id
            regex: ^\d{4}-\d{2}-\d{2}

          spark:
            msg_key: log
            identifier: container_id
            regex: ^\d{4}\/\d{2}\/\d{2} \d{2}:\d{2}:\d{2}.\d{3} \w+
