consts:
  ports:
    "24225": fluentd recv
  tags:
    all-tags: &all-tags
      - test
  envs:
    all-env: &all-env
      - sit
settings:
  acceptor:
    async_out_chan_size: 100000
    sync_out_chan_size: 10000
    max_rotate_id: 372036854775807  # do not change to smaller number
    recvs:
      tenants:
        fluentd:
          type: fluentd
          active_env:
            - sit
          tag_key: tag
          addr: 0.0.0.0:24225
          is_rewrite_tag_from_tag_key: false
  producer:
    discard_chan_size: 50000
    sender_inchan_size: 50000
    tenants:
      fluentd:
        type: fluentd
        active_env:
          - sit
        tags:
          - test.sit
        forks: 3
        addr: fluentd:24225
        msg_batch_size: 10000
        max_wait_sec: 5
        retry_chan_len: 50000
        is_discard_when_blocked: true
  journal:
    buf_dir_path: /data/log/fluentd/go-concator
    buf_file_bytes: 209315200  # 200 MB
    journal_out_chan_len: 100000
    commit_id_chan_len: 500000
  acceptor_filters:
    out_buf_len: 150000
    reenter_chan_len: 5000
    fork: 4
    is_throttle: false
    throttle_max: 10000
    throttle_per_sec: 5000
    tenants:
      spark:
        type: spark
        msg_key: log
        identifier: container_id
        ignore_regex: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2},\d{3} +\[
      spring:
        type: spring
        msg_key: log
        tag_key: tag
        rules:
          - new_tag: cp.{env}
            regexp: ms:cp
          - new_tag: bot.{env}
            regexp: ms_\w+\ {0,}\|
          - new_tag: app.spring.{env}
            regexp: .*
  post_filters:
    reenter_chan_len: 5000
    out_chan_size: 10000
    fork: 4
    tenants:
      default:
        msg_key: log
        max_len: 307200
      forward_tag_rewriter:
        tag_key: tag
        tag: forward-wechat
      es_dispatcher:
        # tags: *all-tags
        tags:
          - kafkabuf
        tag_key: tag
        rewrite_tag_map:
          # es-general
          app.spring.{env}: es-general.{env}
  dispatcher:
    out_chan_size: 10000
  tag_filters:
    internal_chan_size: 10000
    tenants:
      spring:
        type: parser
        tags:
          - test
        msg_key: log
        # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.pateo.qingcloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
        pattern: (?ms)^(?P<time>.{23}) {0,}\| {0,}(?P<app>[^\|]+) {0,}\| {0,}(?P<level>[^\|]+) {0,}\| {0,}(?P<thread>[^\|]+) {0,}\| {0,}(?P<class>[^ ]+) {0,}\| {0,}(?P<line>\d+) {0,}([\|:] {0,}(?P<args>\{.*\}))?([\|:] {0,}(?P<message>.*))?
        is_remove_orig_log: true
        must_include: app
        # ⬇⬇ time
        time_key: time
        time_format: "2006-01-02 15:04:05.000 -0700"
        new_time_format: "2006-01-02T15:04:05.000000Z"
        reserved_time_key: false
        new_time_key: "@timestamp"
        append_time_zone:
          sit: "+0800"
          perf: "+0800"
          uat: "+0800"
          prod: "+0800"
        # ⬇⬇ fields
        add:  # optional
          test:
            datasource: test
      concator:
        type: concator
        config:
          max_length: 100000
        tenants:
          test:
            msg_key: log
            identifier: container_id
            # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.pateo.qingcloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
            regex: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2}\.\d{3} {0,}\|
