consts:
  ports:
    "24225": fluentd recv
  tags:
    all-tags: &all-tags
      - test
  envs:
    all-env: &all-env
      - sit
settings:
  acceptor:
    async_out_chan_size: 100000
    sync_out_chan_size: 10000
    max_rotate_id: 372036854775807  # do not change to smaller number
    recvs:
        # 监听 DC/OS fluentd log-driver 的日志
        fluentd:
          type: fluentd
          active_env: *all-env
          tag_key: tag
          lb_key: container_id
          nfork: 1
          internal_buf_size: 5000
          addr: 0.0.0.0:24225
          is_rewrite_tag_from_tag_key: false
          concat_max_len: 300000
          concat:
            test:
              # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.google.cloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
              msg_key: log
              identifier: container_id
              head_regexp: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2}\.\d{3} *\|
  producer:
    discard_chan_size: 50000
    sender_inchan_size: 50000
    plugins:
      localtest:
        active_env: *all-env
        tags: *all-tags
        type: "stdout"
        forks: 5
        log_level: info
        is_commit: true
        is_discard_when_blocked: false
  journal:
    buf_dir_path: /data/log/fluentd/go-concator
    buf_file_bytes: 209315200  # 200 MB
    journal_out_chan_len: 100000
    commit_id_chan_len: 500000
    is_compress: false
  acceptor_filters:
    out_buf_len: 150000
    reenter_chan_len: 5000
    fork: 4
    is_throttle: false
    throttle_max: 10000
    throttle_per_sec: 5000
    plugins:
      spark:
        type: spark
        msg_key: log
        identifier: container_id
        ignore_regex: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2},\d{3} +\[
      spring:
        type: spring
        msg_key: log
        tag_key: tag
        rules:
          - new_tag: cp.{env}
            regexp: ms:cp
          - new_tag: bot.{env}
            regexp: ms_\w+\ {0,}\|
          - new_tag: app.spring.{env}
            regexp: .*
  post_filters:
    reenter_chan_len: 5000
    out_chan_size: 10000
    fork: 4
    plugins:
      default:
        msg_key: log
        max_len: 307200
  dispatcher:
    out_chan_size: 10000
  tag_filters:
    internal_chan_size: 10000
    plugins:
      spring:
        type: parser
        tags:
          - test
        msg_key: log
        # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.google.cloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
        pattern: (?ms)^(?P<time>.{23}) {0,}\| {0,}(?P<app>[^\|]+) {0,}\| {0,}(?P<level>[^\|]+) {0,}\| {0,}(?P<thread>[^\|]+) {0,}\| {0,}(?P<class>[^ ]+) {0,}\| {0,}(?P<line>\d+) {0,}([\|:] {0,}(?P<args>\{.*\}))?([\|:] {0,}(?P<message>.*))?
        is_remove_orig_log: true
        must_include: app
        # ⬇⬇ time
        time_key: time
        time_format: "2006-01-02 15:04:05.000 -0700"
        new_time_format: "2006-01-02T15:04:05.000000Z"
        reserved_time_key: false
        new_time_key: "@timestamp"
        append_time_zone:
          sit: "+0800"
          perf: "+0800"
          uat: "+0800"
          prod: "+0800"
        # ⬇⬇ fields
        add:  # optional
          test:
            datasource: test
      # concator:
      #   type: concator
      #   config:
      #     max_length: 100000
      #   plugins:
      #     test:
      #       msg_key: log
      #       identifier: container_id
      #       # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.google.cloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
      #       regex: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2}\.\d{3} {0,}\|
