# minimal settings for testing

consts:
  ports:
    "24225": fluentd recv
  tags:
    all-tags: &all-tags
      - test
  envs:
    all-env: &all-env
      - sit
settings:
  acceptor:
    recvs:
      plugins:
        # 监听 DC/OS fluentd log-driver 的日志
        fluentd:
          type: fluentd
          active_env: *all-env
          concat:
            test:
              # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.google.cloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
              msg_key: log
              identifier: container_id
              head_regexp: ^\d{4}-\d{2}-\d{2} +\d{2}:\d{2}:\d{2}\.\d{3} *\|
  producer:
    plugins:
      localtest:
        active_env: *all-env
        tags: *all-tags
        type: "stdout"
        log_level: info
        is_commit: true
  journal:
    buf_dir_path: /data
    is_compress: true
  acceptor_filters:
    plugins:
      spring:
        type: spring
        rules:
          - new_tag: cp.{env}
            regexp: ms:cp
          - new_tag: bot.{env}
            regexp: ms_\w+\ {0,}\|
          - new_tag: app.spring.{env}
            regexp: .*
  post_filters:
    plugins:
      default:
        max_len: 307200
  tag_filters:
    plugins:
      spring:
        type: parser
        tags:
          - test
        # 2018-03-06 16:56:22.514 | mscparea | INFO  | http-nio-8080-exec-1 | com.google.cloud.cp.core.service.impl.CPBusiness.reflectAdapterRequest | 84: test
        pattern: (?ms)^(?P<time>.{23}) {0,}\| {0,}(?P<app>[^\|]+) {0,}\| {0,}(?P<level>[^\|]+) {0,}\| {0,}(?P<thread>[^\|]+) {0,}\| {0,}(?P<class>[^ ]+) {0,}\| {0,}(?P<line>\d+) {0,}([\|:] {0,}(?P<args>\{.*\}))?([\|:] {0,}(?P<message>.*))?
        is_remove_orig_log: true
        must_include: app
        # ⬇⬇ time
        time_format: "2006-01-02 15:04:05.000 -0700"
        append_time_zone:
          sit: "+0800"
          perf: "+0800"
          uat: "+0800"
          prod: "+0800"
        # ⬇⬇ fields
        add:  # optional
          test:
            datasource: test
